# creation rules are evaluated sequentially, the first match wins
creation_rules:
        # upon creation of a file that matches the pattern *.dev.yaml,
        # KMS set A is used
        - path_regex: secret.tfvars$
          kms: 'arn:aws:kms:us-east-1:103478799875:key/0e2e6ea0-8f83-4bf6-9547-591718fc6076'
          pgp: '6D95753CD8638D529786ACB675E98ACBF4F4260C'
