# -*- mode: ruby -*-
# vi: set ft=ruby :

# Pick up the arg passed to the run for wild_vm section
vm_role = ARGV[1]? ARGV[1] : 'base'

# Require >= 1.8.0
Vagrant.require_version ">= 1.8.0"

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # use case for expandability
  case vm_role when "base"

    # Default to a centos 7 vanilla puppetlabs box
    config.vm.box = "puppetlabs/centos-7.0-64-puppet"
    config.vm.box_url = "https://cloud.centos.org/centos/7/vagrant/x86_64/images/CentOS-7-x86_64-Vagrant-1805_01.VirtualBox.box"

    # Generic hostname for all
    config.vm.hostname = "vagrant-test"

    # Creates the base vagrant box.
    # Effectively builds on the centos7 puppetlabs box and runs profile_base
    config.vm.define "base", autostart: false do |vm_base|
      vm_base.vm.provision "puppet" do |puppet|
        puppet.environment = "production"
        puppet.hiera_config_path = "hiera-vagrant.yaml"
        puppet.module_path = ["modules", "contrib/modules"]
        puppet.manifests_path = "manifests"
        puppet.manifest_file = "site.pp"
        puppet.working_directory = "/tmp/vagrant-puppet"
        puppet.options = "--verbose --debug"
        puppet.environment_path = "."
        puppet.facter = {
          "pmc_role"    => "base"
        }
      end
    end
  else
    # Every Vagrant development environment requires a box. You can search for
    # boxes at https://vagrantcloud.com/search.
    config.vm.define :"#{vm_role}", primary: true do |wild_vm|
      wild_vm.vm.box = "puppetlabs/centos-7.0-64-puppet"
      wild_vm.vm.box_url = "https://cloud.centos.org/centos/7/vagrant/x86_64/images/CentOS-7-x86_64-Vagrant-1805_01.VirtualBox.box"
      # wild_vm roles use the pre-built base image
      # boxed from the vm role above
      wild_vm.vm.provision "puppet" do |puppet|
        puppet.environment = "production"
        puppet.hiera_config_path = "hiera-vagrant.yaml"
        puppet.module_path = ["modules", "contrib/modules"]
        puppet.manifests_path = "manifests"
        puppet.manifest_file = "site.pp"
        puppet.working_directory = "/tmp/vagrant-puppet"
        puppet.options = "--verbose --debug"
        puppet.environment_path = "."
        puppet.facter = {
          "role"    => "#{ENV['FACTER_role']}",
          "service" => "#{ENV['FACTER_service']}"        }
      end
    end
  end
end
