#!/usr/bin/env ruby
#^syntax detection

forge "https://forgeapi.puppetlabs.com"

# use dependencies defined in metadata.json
#metadata

# use dependencies defined in Modulefile
# modulefile

# A module from the Puppet Forge
mod 'puppetlabs-stdlib', '4.25.1'
mod 'puppetlabs-motd', '1.9.0'

# CloudPassage Halo
mod 'puppetlabs-apt', '2.4.0'
# mod 'cloudpassage-cloudpassage', '1.0.5'

# Systemd management
mod 'camptocamp-systemd', '1.1.1'

# Java install
# mod 'puppetlabs-java', '2.4.0'

# Apache forge module
# mod 'puppetlabs-apache', '3.1.0'

# Dirtree
# mod 'pltraining/dirtree', '0.3.0'

# Archive
# mod 'puppet-archive', '2.3.0'

# NewRelic
# mod 'claranet-newrelic', '2.4.0'

# A module from git
# mod 'puppetlabs-ntp',
#   :git => 'git://github.com/puppetlabs/puppetlabs-ntp.git'

# A module from a git branch/tag
# mod 'puppetlabs-apt',
#   :git => 'https://github.com/puppetlabs/puppetlabs-apt.git',
#   :ref => '1.4.x'

# A module from Github pre-packaged tarball
# mod 'puppetlabs-apache', '0.6.0', :github_tarball => 'puppetlabs/puppetlabs-apache'
